version: "3"
services:
  service1:
    container_name: service1
    build: ./service1
    ports:
       - "8081:80" 
  service2:
    container_name: service2
    build: ./service2
    ports:
       - "8082:80"
  my-nginx:
    container_name: my-nginx
    build: ./my-nginx
    ports:
       - "80:80"
