version: "3"
services:
  service1:
    build: .
    ports:
       - "8080"
    depends_on:
       - myredis
  myredis:
    container_name: myredis
    image: redis
    ports:
       - "6379:6379"
  service2:
    container_name: service2
    build: ../service2
    ports:
       - "8081:8081"
